from __future__ import annotations

from substrate.umwelt0_phenomenal_contact import ContactAuthorityFlags

from .models import (
    ActionSurfaceSpec,
    ContactChannelDeclaration,
    ContactLossinessRequirement,
    ContactSourceRequirement,
    ContactSpec,
    ContactUncertaintyRequirement,
    EffectSurfaceSpec,
    ForbiddenPayloadRule,
    ProviderSurfaceSpec,
    PublicRefDeclaration,
    UMWELTSChannelKind,
    UMWELTSRefKind,
)


def generic_grid_fixture() -> ContactSpec:
    source_req = ContactSourceRequirement(required=True, source_refs=("src:grid:public",))
    return ContactSpec(
        spec_id="fixture:generic_grid",
        backend_family="generic_grid",
        spec_version="1.0",
        channel_declarations=(
            ContactChannelDeclaration(
                channel_id="ch:grid",
                channel_kind=UMWELTSChannelKind.SYMBOLIC_WORLD,
                public=True,
                requires_source_refs=True,
                requires_lossiness_when_partial=False,
                allows_unknown_refs=False,
                max_refs=24,
                authority_flags=ContactAuthorityFlags(),
            ),
            ContactChannelDeclaration(
                channel_id="ch:body",
                channel_kind=UMWELTSChannelKind.BODY_INTERNAL,
                public=True,
                requires_source_refs=True,
                requires_lossiness_when_partial=False,
                allows_unknown_refs=False,
                max_refs=8,
                authority_flags=ContactAuthorityFlags(),
            ),
            ContactChannelDeclaration(
                channel_id="ch:sys",
                channel_kind=UMWELTSChannelKind.SYSTEM_STATUS,
                public=True,
                requires_source_refs=True,
                requires_lossiness_when_partial=True,
                allows_unknown_refs=False,
                max_refs=8,
                authority_flags=ContactAuthorityFlags(),
            ),
        ),
        public_ref_declarations=(
            PublicRefDeclaration("resource:ore", UMWELTSRefKind.RESOURCE, "ch:grid", source_req),
            PublicRefDeclaration("map_site:cell:1_1", UMWELTSRefKind.MAP_SITE, "ch:grid", source_req),
            PublicRefDeclaration("entity:ore_node", UMWELTSRefKind.ENTITY, "ch:grid", source_req),
            PublicRefDeclaration("hazard:pit", UMWELTSRefKind.HAZARD, "ch:grid", source_req),
            PublicRefDeclaration("body_pressure:hunger", UMWELTSRefKind.BODY_PRESSURE, "ch:body", source_req),
            PublicRefDeclaration("system_status:latency_ok", UMWELTSRefKind.SYSTEM_STATUS, "ch:sys", source_req),
        ),
        action_surface_declarations=(
            ActionSurfaceSpec(
                surface_id="surface:inspect",
                action_kind="inspect",
                channel_id="ch:grid",
                target_ref_kinds=(UMWELTSRefKind.RESOURCE, UMWELTSRefKind.ENTITY),
                source_requirements=source_req,
                authority_flags=ContactAuthorityFlags(),
            ),
            ActionSurfaceSpec(
                surface_id="surface:move_toward",
                action_kind="move_toward",
                channel_id="ch:grid",
                target_ref_kinds=(UMWELTSRefKind.MAP_SITE,),
                source_requirements=source_req,
                authority_flags=ContactAuthorityFlags(),
            ),
        ),
        effect_surface_declarations=(
            EffectSurfaceSpec(
                effect_surface_id="effect:move:delta",
                effect_kind="position_update",
                channel_id="ch:grid",
                request_correlated_allowed=True,
                passive_event_allowed=False,
                required_source_refs=("src:grid:public",),
                required_delta_refs=("delta:position",),
                residue_policy=("residue:path_block",),
                authority_flags=ContactAuthorityFlags(),
            ),
            EffectSurfaceSpec(
                effect_surface_id="effect:ambient:wind",
                effect_kind="passive_event",
                channel_id="ch:sys",
                request_correlated_allowed=False,
                passive_event_allowed=True,
                required_source_refs=("src:grid:public",),
                required_delta_refs=("delta:ambient",),
                residue_policy=(),
                authority_flags=ContactAuthorityFlags(),
            ),
        ),
        provider_declarations=(),
        source_requirements=source_req,
        lossiness_requirements=ContactLossinessRequirement(required_when_partial=True, lossiness_refs=("loss:sampled",)),
        uncertainty_requirements=ContactUncertaintyRequirement(required_when_ambiguous=True, uncertainty_refs=("uncertain:ambiguous",)),
        forbidden_payload_rules=default_forbidden_payload_rules(),
        authority_profile=ContactAuthorityFlags(),
    )


def symbolic_factory_fixture() -> ContactSpec:
    source_req = ContactSourceRequirement(required=True, source_refs=("src:factory:public",))
    return ContactSpec(
        spec_id="fixture:symbolic_factory",
        backend_family="symbolic_factory",
        spec_version="1.0",
        channel_declarations=(
            ContactChannelDeclaration(
                channel_id="ch:world",
                channel_kind=UMWELTSChannelKind.SYMBOLIC_WORLD,
                public=True,
                requires_source_refs=True,
                requires_lossiness_when_partial=False,
                allows_unknown_refs=False,
                max_refs=32,
                authority_flags=ContactAuthorityFlags(),
            ),
            ContactChannelDeclaration(
                channel_id="ch:knowledge",
                channel_kind=UMWELTSChannelKind.KNOWLEDGE_AFFORDANCE,
                public=True,
                requires_source_refs=True,
                requires_lossiness_when_partial=True,
                allows_unknown_refs=False,
                max_refs=16,
                authority_flags=ContactAuthorityFlags(),
            ),
            ContactChannelDeclaration(
                channel_id="ch:status",
                channel_kind=UMWELTSChannelKind.SYSTEM_STATUS,
                public=True,
                requires_source_refs=True,
                requires_lossiness_when_partial=False,
                allows_unknown_refs=False,
                max_refs=12,
                authority_flags=ContactAuthorityFlags(),
            ),
        ),
        public_ref_declarations=(
            PublicRefDeclaration("resource:ore", UMWELTSRefKind.RESOURCE, "ch:world", source_req),
            PublicRefDeclaration("resource:plate", UMWELTSRefKind.RESOURCE, "ch:world", source_req),
            PublicRefDeclaration("station:smelter", UMWELTSRefKind.STATION, "ch:world", source_req),
            PublicRefDeclaration("inventory:main", UMWELTSRefKind.INVENTORY, "ch:world", source_req),
            PublicRefDeclaration("knowledge_hint:manual_slot_filter", UMWELTSRefKind.KNOWLEDGE_HINT, "ch:knowledge", source_req),
            PublicRefDeclaration("provider_claim:manual_hint", UMWELTSRefKind.PROVIDER_CLAIM, "ch:knowledge", source_req),
            PublicRefDeclaration("system_status:power_ok", UMWELTSRefKind.SYSTEM_STATUS, "ch:status", source_req),
        ),
        action_surface_declarations=(
            ActionSurfaceSpec(
                surface_id="surface:use_station",
                action_kind="use_station",
                channel_id="ch:world",
                target_ref_kinds=(UMWELTSRefKind.STATION,),
                required_resource_ref_kinds=(UMWELTSRefKind.RESOURCE,),
                source_requirements=source_req,
                authority_flags=ContactAuthorityFlags(),
            ),
        ),
        effect_surface_declarations=(
            EffectSurfaceSpec(
                effect_surface_id="effect:station_output",
                effect_kind="request_correlated_output",
                channel_id="ch:world",
                request_correlated_allowed=True,
                passive_event_allowed=False,
                required_source_refs=("src:factory:public",),
                required_delta_refs=("delta:inventory",),
                residue_policy=("residue:missing_input",),
                authority_flags=ContactAuthorityFlags(),
            ),
        ),
        provider_declarations=(
            ProviderSurfaceSpec(
                provider_id="provider:manual",
                provider_kind="manual_tooltip",
                channel_id="ch:knowledge",
                authority_class="hint_only",
                source_requirements=source_req,
                hint_only=True,
                truth_authority=False,
                can_mature_recipe=False,
                can_assign_value=False,
                can_select_action=False,
            ),
        ),
        source_requirements=source_req,
        lossiness_requirements=ContactLossinessRequirement(required_when_partial=True, lossiness_refs=("loss:provider_declared",)),
        uncertainty_requirements=ContactUncertaintyRequirement(required_when_ambiguous=True, uncertainty_refs=("uncertain:provider_partial",)),
        forbidden_payload_rules=default_forbidden_payload_rules(),
        authority_profile=ContactAuthorityFlags(),
    )


def language_sensor_fixture() -> ContactSpec:
    source_req = ContactSourceRequirement(required=True, source_refs=("src:lang_sensor:public",))
    return ContactSpec(
        spec_id="fixture:language_sensor",
        backend_family="language_sensor",
        spec_version="1.0",
        channel_declarations=(
            ContactChannelDeclaration(
                channel_id="ch:language",
                channel_kind=UMWELTSChannelKind.LANGUAGE_CONTACT,
                public=True,
                requires_source_refs=True,
                requires_lossiness_when_partial=False,
                allows_unknown_refs=False,
                max_refs=20,
                authority_flags=ContactAuthorityFlags(),
            ),
            ContactChannelDeclaration(
                channel_id="ch:sensory",
                channel_kind=UMWELTSChannelKind.SENSORY_CANDIDATE,
                public=True,
                requires_source_refs=True,
                requires_lossiness_when_partial=True,
                allows_unknown_refs=False,
                max_refs=20,
                authority_flags=ContactAuthorityFlags(),
            ),
            ContactChannelDeclaration(
                channel_id="ch:social",
                channel_kind=UMWELTSChannelKind.SOCIAL_EXTERNAL_ACTOR,
                public=True,
                requires_source_refs=True,
                requires_lossiness_when_partial=False,
                allows_unknown_refs=False,
                max_refs=12,
                authority_flags=ContactAuthorityFlags(),
            ),
        ),
        public_ref_declarations=(
            PublicRefDeclaration("language_utterance:msg_1", UMWELTSRefKind.LANGUAGE_UTTERANCE, "ch:language", source_req),
            PublicRefDeclaration("speech_act_candidate:warn_1", UMWELTSRefKind.SPEECH_ACT_CANDIDATE, "ch:language", source_req),
            PublicRefDeclaration("sensory_candidate:visual_1", UMWELTSRefKind.SENSORY_CANDIDATE, "ch:sensory", source_req),
            PublicRefDeclaration("sensory_candidate:audio_1", UMWELTSRefKind.SENSORY_CANDIDATE, "ch:sensory", source_req),
            PublicRefDeclaration("provider_claim:other_actor_hint", UMWELTSRefKind.PROVIDER_CLAIM, "ch:social", source_req),
        ),
        action_surface_declarations=(),
        effect_surface_declarations=(),
        provider_declarations=(),
        source_requirements=source_req,
        lossiness_requirements=ContactLossinessRequirement(required_when_partial=True, lossiness_refs=("loss:sensory_sampled",)),
        uncertainty_requirements=ContactUncertaintyRequirement(required_when_ambiguous=True, uncertainty_refs=("uncertain:testimony",)),
        forbidden_payload_rules=default_forbidden_payload_rules(),
        authority_profile=ContactAuthorityFlags(),
    )


def default_forbidden_payload_rules() -> tuple[ForbiddenPayloadRule, ...]:
    return (
        ForbiddenPayloadRule(
            rule_id="planner_payload",
            reason="spec cannot embed planner/action selection",
            blocked_tokens=(
                "selected_action",
                "preferred_action",
                "if_then_policy",
                "route_plan",
                "goal_selection",
                "behavior_tree",
                "scripted_solution",
                "factory_sequence",
                "solution_sequence",
                "factory_steps",
                "ordered_plan",
                "required_action_order",
                "craft_then_place_then_run",
                "intrinsic_need",
                "drive_weight",
                "homeostatic_rule",
                "subject_goal",
                "badness_function",
            ),
            applies_to=("spec", "action_surface", "metadata"),
        ),
        ForbiddenPayloadRule(
            rule_id="recipe_oracle_payload",
            reason="spec cannot embed recipe oracle truth",
            blocked_tokens=(
                "true_recipe",
                "recipe_truth",
                "exact_hidden_recipe",
                "authoritative_recipe_table",
                "hidden_transformation_truth",
            ),
            applies_to=("spec", "ref", "provider", "metadata"),
        ),
        ForbiddenPayloadRule(
            rule_id="backend_truth_payload",
            reason="spec cannot carry hidden backend truth",
            blocked_tokens=(
                "worldstate",
                "full_world_state",
                "hidden_map",
                "full_map",
                "backend_object_id",
                "hidden_label",
                "eval_label",
                "scenario_label_as_basis",
            ),
            applies_to=("spec", "ref", "provider", "metadata"),
        ),
    )
