from __future__ import annotations

from substrate.targeted_clarification.models import (
    InterventionBundle,
    InterventionGateDecision,
    TargetedClarificationResult,
    TargetedClarificationTelemetry,
)


def build_targeted_clarification_telemetry(
    *,
    bundle: InterventionBundle,
    source_lineage: tuple[str, ...],
    attempted_paths: tuple[str, ...],
    downstream_gate: InterventionGateDecision,
    causal_basis: str,
) -> TargetedClarificationTelemetry:
    return TargetedClarificationTelemetry(
        source_lineage=source_lineage,
        source_acquisition_ref=bundle.source_acquisition_ref,
        source_framing_ref=bundle.source_framing_ref,
        source_perspective_chain_ref=bundle.source_perspective_chain_ref,
        source_applicability_ref=bundle.source_applicability_ref,
        source_runtime_graph_ref=bundle.source_runtime_graph_ref,
        source_grounded_ref=bundle.source_grounded_ref,
        source_dictum_ref=bundle.source_dictum_ref,
        source_syntax_ref=bundle.source_syntax_ref,
        source_surface_ref=bundle.source_surface_ref,
        intervention_record_count=len(bundle.intervention_records),
        intervention_statuses=tuple(dict.fromkeys(record.intervention_status.value for record in bundle.intervention_records)),
        uncertainty_classes=tuple(dict.fromkeys(record.uncertainty_class.value for record in bundle.intervention_records)),
        low_coverage_mode=bundle.low_coverage_mode,
        low_coverage_reasons=bundle.low_coverage_reasons,
        ambiguity_reasons=bundle.ambiguity_reasons,
        l06_update_proposal_absent=bundle.l06_update_proposal_absent,
        repair_trigger_basis_incomplete=bundle.repair_trigger_basis_incomplete,
        response_realization_contract_absent=bundle.response_realization_contract_absent,
        answer_binding_consumer_absent=bundle.answer_binding_consumer_absent,
        attempted_paths=attempted_paths,
        downstream_gate=downstream_gate,
        causal_basis=causal_basis,
    )


def targeted_clarification_result_snapshot(result: TargetedClarificationResult) -> dict[str, object]:
    bundle = result.bundle
    return {
        "confidence": result.confidence,
        "partial_known": result.partial_known,
        "partial_known_reason": result.partial_known_reason,
        "abstain": result.abstain,
        "abstain_reason": result.abstain_reason,
        "no_final_semantic_closure": result.no_final_semantic_closure,
        "bundle": {
            "source_acquisition_ref": bundle.source_acquisition_ref,
            "source_framing_ref": bundle.source_framing_ref,
            "source_perspective_chain_ref": bundle.source_perspective_chain_ref,
            "source_applicability_ref": bundle.source_applicability_ref,
            "source_runtime_graph_ref": bundle.source_runtime_graph_ref,
            "source_grounded_ref": bundle.source_grounded_ref,
            "source_dictum_ref": bundle.source_dictum_ref,
            "source_syntax_ref": bundle.source_syntax_ref,
            "source_surface_ref": bundle.source_surface_ref,
            "linked_acquisition_ids": bundle.linked_acquisition_ids,
            "linked_framing_ids": bundle.linked_framing_ids,
            "ambiguity_reasons": bundle.ambiguity_reasons,
            "low_coverage_mode": bundle.low_coverage_mode,
            "low_coverage_reasons": bundle.low_coverage_reasons,
            "l06_update_proposal_absent": bundle.l06_update_proposal_absent,
            "repair_trigger_basis_incomplete": bundle.repair_trigger_basis_incomplete,
            "response_realization_contract_absent": bundle.response_realization_contract_absent,
            "answer_binding_consumer_absent": bundle.answer_binding_consumer_absent,
            "answer_binding_ready": bundle.answer_binding_ready,
            "answer_binding_hooks": bundle.answer_binding_hooks,
            "intervention_requires_target_binding_read": bundle.intervention_requires_target_binding_read,
            "downstream_lockouts_must_be_read": bundle.downstream_lockouts_must_be_read,
            "clarification_not_equal_realized_question": bundle.clarification_not_equal_realized_question,
            "asked_question_not_equal_resolved_uncertainty": bundle.asked_question_not_equal_resolved_uncertainty,
            "downstream_authority_degraded": bundle.downstream_authority_degraded,
            "no_final_semantic_closure": bundle.no_final_semantic_closure,
            "reason": bundle.reason,
            "intervention_records": tuple(
                {
                    "intervention_id": record.intervention_id,
                    "source_record_ids": record.source_record_ids,
                    "uncertainty_target_id": record.uncertainty_target_id,
                    "uncertainty_class": record.uncertainty_class.value,
                    "intervention_status": record.intervention_status.value,
                    "ask_policy": {
                        "should_ask": record.ask_policy.should_ask,
                        "urgency": record.ask_policy.urgency,
                        "reason": record.ask_policy.reason,
                    },
                    "abstain_policy": {
                        "should_abstain": record.abstain_policy.should_abstain,
                        "mode": record.abstain_policy.mode,
                        "reason": record.abstain_policy.reason,
                    },
                    "guarded_continue_policy": {
                        "should_continue": record.guarded_continue_policy.should_continue,
                        "required_limits": record.guarded_continue_policy.required_limits,
                        "reason": record.guarded_continue_policy.reason,
                    },
                    "minimal_question_spec": {
                        "spec_id": record.minimal_question_spec.spec_id,
                        "clarification_intent": {
                            "intent_id": record.minimal_question_spec.clarification_intent.intent_id,
                            "target_contrast": record.minimal_question_spec.clarification_intent.target_contrast,
                            "allowed_semantic_scope": record.minimal_question_spec.clarification_intent.allowed_semantic_scope,
                            "allowed_answer_form": record.minimal_question_spec.clarification_intent.allowed_answer_form,
                            "conceptual_stretch_bound": record.minimal_question_spec.clarification_intent.conceptual_stretch_bound,
                        },
                        "questionability_reason": record.minimal_question_spec.questionability_reason,
                        "forbidden_assumptions": record.minimal_question_spec.forbidden_assumptions,
                        "preferred_answer_forbidden": record.minimal_question_spec.preferred_answer_forbidden,
                        "realization_contract_marker": record.minimal_question_spec.realization_contract_marker,
                    },
                    "forbidden_presuppositions": record.forbidden_presuppositions,
                    "expected_evidence_gain": {
                        "gain_score": record.expected_evidence_gain.gain_score,
                        "gain_level": record.expected_evidence_gain.gain_level,
                        "gain_reason": record.expected_evidence_gain.gain_reason,
                        "impact_scope": record.expected_evidence_gain.impact_scope,
                        "worth_cost": record.expected_evidence_gain.worth_cost,
                    },
                    "downstream_lockouts": record.downstream_lockouts,
                    "reopen_conditions": record.reopen_conditions,
                    "decision": {
                        "selected_status": record.decision.selected_status.value,
                        "decision_basis": record.decision.decision_basis,
                        "blocking_uncertainty": record.decision.blocking_uncertainty,
                        "questionability_sufficient": record.decision.questionability_sufficient,
                        "cost_worthwhile": record.decision.cost_worthwhile,
                    },
                    "confidence": record.confidence,
                    "provenance": record.provenance,
                }
                for record in bundle.intervention_records
            ),
        },
        "telemetry": {
            "source_lineage": result.telemetry.source_lineage,
            "source_acquisition_ref": result.telemetry.source_acquisition_ref,
            "source_framing_ref": result.telemetry.source_framing_ref,
            "source_perspective_chain_ref": result.telemetry.source_perspective_chain_ref,
            "source_applicability_ref": result.telemetry.source_applicability_ref,
            "source_runtime_graph_ref": result.telemetry.source_runtime_graph_ref,
            "source_grounded_ref": result.telemetry.source_grounded_ref,
            "source_dictum_ref": result.telemetry.source_dictum_ref,
            "source_syntax_ref": result.telemetry.source_syntax_ref,
            "source_surface_ref": result.telemetry.source_surface_ref,
            "intervention_record_count": result.telemetry.intervention_record_count,
            "intervention_statuses": result.telemetry.intervention_statuses,
            "uncertainty_classes": result.telemetry.uncertainty_classes,
            "low_coverage_mode": result.telemetry.low_coverage_mode,
            "low_coverage_reasons": result.telemetry.low_coverage_reasons,
            "ambiguity_reasons": result.telemetry.ambiguity_reasons,
            "l06_update_proposal_absent": result.telemetry.l06_update_proposal_absent,
            "repair_trigger_basis_incomplete": result.telemetry.repair_trigger_basis_incomplete,
            "response_realization_contract_absent": result.telemetry.response_realization_contract_absent,
            "answer_binding_consumer_absent": result.telemetry.answer_binding_consumer_absent,
            "attempted_paths": result.telemetry.attempted_paths,
            "downstream_gate": {
                "accepted": result.telemetry.downstream_gate.accepted,
                "usability_class": result.telemetry.downstream_gate.usability_class.value,
                "restrictions": result.telemetry.downstream_gate.restrictions,
                "reason": result.telemetry.downstream_gate.reason,
                "accepted_intervention_ids": result.telemetry.downstream_gate.accepted_intervention_ids,
                "rejected_intervention_ids": result.telemetry.downstream_gate.rejected_intervention_ids,
            },
            "causal_basis": result.telemetry.causal_basis,
        },
    }
